{
 "title": "K8s Cluster Monitoring",
 "description": "new",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "component", "query": { "query": "label_values(job)" } },
   { "name": "node", "label": "node", "query": { "query": "label_values(node)" } },
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Api server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "apiserver request rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[5m])) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "kube-apiserver request latency",
   "type": "graph",
   "description": "95th percentile request latency for Kubernetes apiserver component",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "p50 "
    }
   ]
  },
  { "title": "ETCD Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Etcd Members",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etcd_server_id{job=~\"$cluster\"})",
     "legendFormat": "members"
    }
   ]
  },
  {
   "title": "Etcd has a leader?",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_has_leader{job=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "The number of leader changes seen",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total{job=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "(max-current) DB Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(etcd_server_quota_backend_bytes{job=~\"$cluster\"})-(etcd_mvcc_db_total_size_in_bytes{job=~\"$cluster\"})",
     "legendFormat": "{{ pod }} DB Size"
    }
   ]
  },
  {
   "title": "Current DB Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} DB Size"
    }
   ]
  },
  {
   "title": "Current Used DB Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_use_in_bytes{job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} DB Size"
    }
   ]
  },
  {
   "title": "etcd request latency",
   "type": "graph",
   "description": "etcd request latency (p95)",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Info",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$cluster\"}"
    },
    {
     "expr": "(etcd_mvcc_db_total_size_in_bytes{job=~\"$cluster\"} / etcd_server_quota_backend_bytes{job=~\"$cluster\"})*100"
    },
    {
     "expr": "sum(etcd_debugging_mvcc_keys_total{job=~\"$cluster\"}) by (instance)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=~\"$cluster\"}[5m])) by (instance, le))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job=~\"$cluster\"}[5m])) by (instance, le))"
    },
    {
     "expr": "sum(etcd_server_is_leader{job=~\"$cluster\"}) by (instance)"
    },
    {
     "expr": "sum(etcd_debugging_mvcc_db_compaction_keys_total{job=~\"$cluster\"}) by (instance)"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "kubelet status Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kubelet_node_name{node=~\"$node\"}==1)/sum(kube_node_info{node=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "coredns status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(coredns_build_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "kube-controller status Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(leader_election_master_status{name=\"kube-controller-manager\"})/sum(kube_node_info{node=~\"$node\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status kube-scheduler",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(leader_election_master_status{name=\"kube-scheduler\"})/sum(kube_node_info{node=~\"$node\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Number Of Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total number Of Master nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_node_role{role!=\"worker\"})"
    }
   ]
  },
  {
   "title": "Number Of Worker nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_node_role{role=\"worker\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Master nodes Availability ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_role{role=\"control-plane\"}==1)/sum(kube_node_info{node=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker nodes Availability ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(count(kube_node_role{role=\"worker\"}==1))/(sum(kube_node_role{role=\"worker\"})) or vector(0)"
    }
   ]
  },
  {
   "title": "Nodes Out of Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", node=~\"$node\", status=\"true\"}) or vector(0)"
    }
   ]
  },
  { "title": "Deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Updated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
    }
   ]
  }
 ]
}