apiVersion: v2
appVersion: "0.1"
description: Complete Monitoring stack for cloud and kubernetes components
keywords:
- monitoring
name: monitoring-stack
type: application
version: 0.1.0
dependencies:
- name: grafana
  version: 6.58.6
  repository: 'file://charts/grafana'
  condition: grafana.enabled
- condition: victoria-metrics-cluster.enabled
  name: victoria-metrics-cluster
  repository: 'file://charts/victoriametrics'
  version: 0.11.4
- condition: victoria-metrics-agent.enabled
  name: victoria-metrics-agent
  repository: 'file://charts/vmAgent'
  version: 0.8.40
- name: kube-state-metrics
  version: "5.12.*"
  repository: 'file://charts/kube-state-metrics'
  condition: kube-state-metrics.enabled
- name: prometheus-node-exporter
  version: "4.23.*"
  repository: 'file://charts/prometheus-node-exporter'
  condition: prometheus-node-exporter.enabled
- name: loki
  version: 2.16.0
  repository: 'file://charts/loki'
  condition: loki.enabled
- name: promtail
  version: 6.15.5
  repository: 'file://charts/promtail'
  condition: promtail.enabled
- name: prometheus
  version: 25.18.0
  repository: 'file://charts/prometheus'
  condition: prometheus.enabled
