apiVersion: v1
kind: ConfigMap
metadata:
  name: alerts-configmap
  labels:
    grafana: alerting
  namespace: {{ .Release.Namespace | quote }}
data:
{{- (.Files.Glob "files/alerts/**.yaml").AsConfig | nindent 4 }}