{
 "title": "Centralised Instance Monitoring Based on UUID",
 "description": "This is complete dashboard to monitor libvirt hypervisors and virtual machines",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   { "name": "datacenter", "label": "datacenter", "query": { "query": "label_values(datacenter)" } },
   {
    "name": "vm_uuid",
    "query": {
     "query": "label_values(libvirt_domain_info_vstate{datacenter=~\"$datacenter.*\"},uuid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU % usage on VM based on UUID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(libvirt_domain_info_cpu_time_seconds_total{uuid=\"$vm_uuid\", datacenter=\"$datacenter\"}[5m] ) *100 / 1000000000 / libvirt_domain_info_virtual_cpus{uuid=\"$vm_uuid\", datacenter=\"$datacenter\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used % based on UUID",
   "type": "timeseries",
   "description": "The amount of memory in percent, that used by domain.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_used_percent{uuid=\"$vm_uuid\", datacenter=\"$datacenter\"}",
     "legendFormat": "{{instance_name}}-{{uuid}}-{{project_name}}"
    }
   ]
  },
  {
   "title": "Available memory inside vm based on UUID in GB",
   "type": "timeseries",
   "description": "How much the balloon can be inflated without pushing the guest system to swap, corresponds to 'Available' in /proc/meminfo",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_usable_bytes{uuid=\"$vm_uuid\", datacenter=\"$datacenter\"}/1024/1024/1024",
     "legendFormat": "{{instance_name}}-{{uuid}}-{{project_name}}"
    }
   ]
  },
  {
   "title": "Available memory inside vm based on UUID in MB",
   "type": "timeseries",
   "description": "How much the balloon can be inflated without pushing the guest system to swap, corresponds to 'Available' in /proc/meminfo",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_usable_bytes{uuid=\"$vm_uuid\", datacenter=\"$datacenter\"}/1024/1024",
     "legendFormat": "{{instance_name}}-{{uuid}}-{{project_name}}"
    }
   ]
  },
  {
   "title": "Available memory inside vm based on UUID in KB",
   "type": "timeseries",
   "description": "How much the balloon can be inflated without pushing the guest system to swap, corresponds to 'Available' in /proc/meminfo",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_usable_bytes{uuid=\"$vm_uuid\", datacenter=\"$datacenter\"}/1024",
     "legendFormat": "{{instance_name}}-{{uuid}}-{{project_name}}"
    }
   ]
  },
  {
   "title": "Memory used inside vm based on UUID in GB",
   "type": "timeseries",
   "description": "How much the balloon can be inflated without pushing the guest system to swap, corresponds to 'Available' in /proc/meminfo",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(libvirt_domain_memory_stats_available_bytes{uuid=\"$vm_uuid\", datacenter=\"$datacenter\"}-libvirt_domain_memory_stats_usable_bytes{uuid=\"$vm_uuid\", datacenter=\"$datacenter\"})/1024/1024/1024",
     "legendFormat": "{{instance_name}}-{{uuid}}-{{project_name}}"
    }
   ]
  },
  {
   "title": "Memory used inside vm based on UUID in MB",
   "type": "timeseries",
   "description": "How much the balloon can be inflated without pushing the guest system to swap, corresponds to 'Available' in /proc/meminfo",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(libvirt_domain_memory_stats_available_bytes{uuid=\"$vm_uuid\", datacenter=\"$datacenter\"}-libvirt_domain_memory_stats_usable_bytes{uuid=\"$vm_uuid\", datacenter=\"$datacenter\"})/1024/1024",
     "legendFormat": "{{instance_name}}-{{uuid}}-{{project_name}}"
    }
   ]
  },
  {
   "title": "Memory used inside vm based on UUID in KB",
   "type": "timeseries",
   "description": "How much the balloon can be inflated without pushing the guest system to swap, corresponds to 'Available' in /proc/meminfo",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "(libvirt_domain_memory_stats_available_bytes{uuid=\"$vm_uuid\", datacenter=\"$datacenter\"}-libvirt_domain_memory_stats_usable_bytes{uuid=\"$vm_uuid\", datacenter=\"$datacenter\"})/1024",
     "legendFormat": "{{instance_name}}-{{uuid}}-{{project_name}}"
    }
   ]
  },
  {
   "title": "Memory  % available inside vm based on UUID",
   "type": "timeseries",
   "description": "How much the balloon can be inflated without pushing the guest system to swap, corresponds to 'Available' in /proc/meminfo",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100-(libvirt_domain_memory_stats_used_percent{uuid=\"$vm_uuid\", datacenter=\"$datacenter\"})",
     "legendFormat": "{{instance_name}}-{{uuid}}-{{project_name}}"
    }
   ]
  },
  {
   "title": "Network Packets Transmited based on UUID in KiB",
   "type": "timeseries",
   "description": "Number of bytes transmitted on a network interface, in bytes.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "(libvirt_domain_interface_stats_transmit_bytes_total{uuid=\"$vm_uuid\", datacenter=\"$datacenter\"})/1024",
     "legendFormat": "{{instance_name}}--({{instance}})- transmit"
    }
   ]
  },
  {
   "title": "Network Packets Transmited based on UUID in MiB",
   "type": "timeseries",
   "description": "Number of bytes transmitted on a network interface, in bytes.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "(libvirt_domain_interface_stats_transmit_bytes_total{uuid=\"$vm_uuid\", datacenter=\"$datacenter\"})/1024/1024",
     "legendFormat": "{{instance_name}}--({{instance}})- transmit"
    }
   ]
  },
  {
   "title": "Network Packets Transmited based on UUID in GiB",
   "type": "timeseries",
   "description": "Number of bytes transmitted on a network interface, in bytes.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "(libvirt_domain_interface_stats_transmit_bytes_total{uuid=\"$vm_uuid\", datacenter=\"$datacenter\"})/1024/1024/1024",
     "legendFormat": "{{instance_name}}--({{instance}})- transmit"
    }
   ]
  },
  {
   "title": "Network Packets Recieved based on UUID in KiB",
   "type": "timeseries",
   "description": "Number of packets received on a network interface.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "(libvirt_domain_interface_stats_receive_packets_total{uuid=\"$vm_uuid\", datacenter=\"$datacenter\"})/1024",
     "legendFormat": "{{instance_name}}--({{instance}})- receive"
    }
   ]
  },
  {
   "title": "Network Packets Recieved based on UUID in MiB",
   "type": "timeseries",
   "description": "Number of packets received on a network interface.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "(libvirt_domain_interface_stats_receive_packets_total{uuid=\"$vm_uuid\", datacenter=\"$datacenter\"})/1024/1024",
     "legendFormat": "{{instance_name}}--({{instance}})- receive"
    }
   ]
  },
  {
   "title": "Network Packets Recieved based on UUID in GiB",
   "type": "timeseries",
   "description": "Number of packets received on a network interface.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "(libvirt_domain_interface_stats_receive_packets_total{uuid=\"$vm_uuid\", datacenter=\"$datacenter\"})/1024/1024/1024",
     "legendFormat": "{{instance_name}}--({{instance}})- receive"
    }
   ]
  }
 ]
}