{
 "title": "Centralised Instance Monitoring",
 "description": "This is complete dashboard to monitor libvirt hypervisors and virtual machines",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(libvirt_up, instance)"
    }
   },
   {
    "name": "vm_name",
    "query": {
     "query": "label_values(libvirt_domain_info_vstate{instance=~\"$instance.*\"}, instance_name)"
    }
   },
   {
    "name": "domain",
    "query": {
     "query": "label_values(libvirt_domain_info_vstate{instance=~\"$instance.*\"}, domain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU % usage on VM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "irate(libvirt_domain_info_cpu_time_seconds_total{instance_name=\"$vm_name\"}[5m] ) *100 / 1000000000 / libvirt_domain_info_virtual_cpus{instance_name=\"$vm_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Count VM  in Active+Pause+Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_total_vms{})-count(libvirt_domain_memory_stats_used_percent==0)",
     "legendFormat": "{{ instance }} --Hostname"
    }
   ]
  },
  {
   "title": "VM in Error State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Total Number of VM  in shutoff state",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_memory_stats_used_percent==0)",
     "legendFormat": "{{ instance }} -- {{ instane-name }}"
    }
   ]
  },
  {
   "title": "RAM and Disk usage on Running  vms",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_available_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "total"
    },
    {
     "expr": "(libvirt_domain_memory_stats_used_percent_bytes{instance=~\"$instance.*\"} * libvirt_domain_memory_stats_available_bytes{instance=~\"$instance.*\"}) / 100",
     "legendFormat": "used"
    },
    {
     "expr": "libvirt_domain_memory_stats_used_percent{instance=~\"$instance.*\"}",
     "legendFormat": "used %"
    },
    {
     "expr": "libvirt_domain_block_stats_physicalsize_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "Disk Size"
    },
    {
     "expr": "rate(node_cpu_guest_seconds_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Details of VM in shutoff state",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_available_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "total"
    },
    {
     "expr": "(libvirt_domain_memory_stats_used_percent_bytes{instance=~\"$instance.*\"} * libvirt_domain_memory_stats_available_bytes{instance=~\"$instance.*\"}) / 100",
     "legendFormat": "used"
    },
    {
     "expr": "libvirt_domain_memory_stats_used_percent{instance=~\"$instance.*\"}",
     "legendFormat": "used %"
    },
    {
     "expr": "libvirt_domain_block_stats_physicalsize_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "Disk Size"
    }
   ]
  },
  {
   "title": "CPU load on physical host",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$instance.*\",job=\"node_exporter\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"$instance.*\",job=\"node_exporter\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$instance.*\",job=\"node_exporter\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$instance.*\",job=\"node_exporter\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$instance.*\",job=\"node_exporter\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$instance.*\",job=\"node_exporter\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "FREE memory on physical host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance.*\",job=\"node_exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Stats ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Used percent",
   "type": "graph",
   "description": "The amount of memory in percent, that used by domain.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_used_percent{instance_name=~\"$vm_name\"}",
     "legendFormat": "{{instance_name}}----({{project_name}})"
    }
   ]
  },
  {
   "title": "Total memory inside vm",
   "type": "graph",
   "description": "The total amount of usable memory as seen by the domain. This value may be less than the amount of memory assigned to the domain if a balloon driver is in use or if the guest OS does not initialize all assigned pages. This value is expressed in kB.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_available_bytes{instance_name=~\"$vm_name\"}",
     "legendFormat": "{{instance_name}}--({{instance}})"
    }
   ]
  },
  {
   "title": "Available memory inside vm",
   "type": "graph",
   "description": "How much the balloon can be inflated without pushing the guest system to swap, corresponds to 'Available' in /proc/meminfo",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_usable_bytes{instance_name=~\"$vm_name\"}",
     "legendFormat": "{{instance_name}}---({{instance}})"
    }
   ]
  },
  {
   "title": "Completely unused memory",
   "type": "graph",
   "description": "The amount of memory left completely unused by the system. Memory that is available but used for reclaimable caches should NOT be reported as free. This value is expressed in kB.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_unused_bytes{instance_name=~\"$vm_name\"}",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Current balloon value",
   "type": "graph",
   "description": "Current balloon value (in KB).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_actual_balloon_bytes{instance_name=~\"$vm_name\"}",
     "legendFormat": "{{instance_name}}----({{instance}})"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "graph",
   "description": "The amount of memory, that can be quickly reclaimed without additional I/O (in kB).Typically these pages are used for caching files from disk.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_disk_cache_bytes{instance_name=~\"$vm_name\"}",
     "legendFormat": "{{instance_name}}-----({{instance}})"
    }
   ]
  },
  {
   "title": "Major fault",
   "type": "graph",
   "description": "Page faults occur when a process makes a valid access to virtual memory that is not available. When servicing the page fault, if disk IO is required, it is considered a major fault.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_major_fault_total{instance_name=~\"$vm_name\"}",
     "legendFormat": "{{instance_name}}--({{instance}})"
    }
   ]
  },
  {
   "title": "Minor fault",
   "type": "graph",
   "description": "Page faults occur when a process makes a valid access to virtual memory that is not available. When servicing the page not fault, if disk IO is required, it is considered a minor fault.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_minor_fault_total{instance_name=~\"$vm_name\"}",
     "legendFormat": "{{instance_name}}--({{instance}})"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "graph",
   "description": "Resident Set Size of the process running the domain. This value is in kB",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_rss_bytes{instance_name=~\"$vm_name\"}",
     "legendFormat": "{{instance_name}}--({{instance}})"
    }
   ]
  },
  {
   "title": "Network Interface Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "description": "Number of bytes transmitted on a network interface, in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_interface_stats_transmit_bytes_total{instance=~\"$instance.*\", instance_name=~\"$vm_name\"}[5m])",
     "legendFormat": "{{instance_name}}--({{instance}})- transmit"
    },
    {
     "expr": "irate(libvirt_domain_interface_stats_receive_bytes_total{instance=~\"$instance.*\", instance_name=~\"$domain\"}[5m])",
     "legendFormat": "{{instance_name}}--({{instance}})- receive"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "graph",
   "description": "Number of packets received on a network interface.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_receive_packets_total{instance=~\"$instance.*\", instance_name=~\"$vm_name\"}[5m])",
     "legendFormat": "{{instance_name}}--({{instance}})- receive"
    },
    {
     "expr": "rate(libvirt_domain_interface_stats_transmit_packets_total{instance=~\"$instance.*\", instance_name=~\"$domain\"}[5m])",
     "legendFormat": "{{domain}} - transfer"
    }
   ]
  },
  {
   "title": "Network drops",
   "type": "graph",
   "description": "Number of packet transmit drops on a network interface.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_transmit_drops_total{instance=~\"$instance.*\", instance_name=~\"$vm_name\"}[5m])",
     "legendFormat": "{{instance_name}}--({{instance}})- transmit"
    },
    {
     "expr": "rate(libvirt_domain_interface_stats_receive_drops_total{instance=~\"$instance.*\", instance_name=~\"$domain\"}[5m])",
     "legendFormat": "{{instance_name}}--({{instance}})-receive"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "description": "Number of packet receive errors on a network interface.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_receive_errors_total{instance=~\"$instance.*\", instance_name=~\"$vm_name\"}[5m])",
     "legendFormat": "{{instance_name}}--({{instance}})-receive"
    },
    {
     "expr": "rate(libvirt_domain_interface_stats_transmit_errors_total{instance=~\"$instance.*\", instance_name=~\"$domain\"}[5m])",
     "legendFormat": "{{instance_name}}--({{instance}}) - transmit"
    }
   ]
  },
  {
   "title": "Block Stats ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Write and read requests",
   "type": "graph",
   "description": "Number of write requests to a block device.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_block_stats_write_requests_total{instance=~\"$instance.*\", instance_name=~\"$vm_name\"}[5m])",
     "legendFormat": "{{instance_name}}--({{instance}}) - write"
    },
    {
     "expr": "irate(libvirt_domain_block_stats_read_requests_total{instance=~\"$instance.*\", instance_name=~\"$domain\"}[5m])",
     "legendFormat": "{{instance_name}}--({{instance}})- read"
    }
   ]
  },
  {
   "title": "Write and read time",
   "type": "graph",
   "description": "Total time (ns) spent on writes on a block device, in ns, that is, 1/1,000,000,000 of a second, or 10−9 seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_block_stats_write_time_seconds_total{instance=~\"$instance.*\", instance_name=~\"$vm_name\"}[5m])",
     "legendFormat": "{{instance_name}}--({{instance}})-write"
    },
    {
     "expr": "irate(libvirt_domain_block_stats_read_time_seconds_total{instance=~\"$instance.*\", instance_name=~\"$domain\"}[5m])",
     "legendFormat": "{{instance_name}}--({{instance}}) - read"
    }
   ]
  },
  {
   "title": "Write and read bytes",
   "type": "graph",
   "description": "Number of bytes written to a block device, in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_block_stats_write_bytes_total{instance=~\"$instance.*\", instance_name=~\"$vm_name\"}[5m])",
     "legendFormat": "{{instance_name}}--({{instance}})- write"
    },
    {
     "expr": "irate(libvirt_domain_block_stats_read_bytes_total{instance=~\"$instance.*\", instance_name=~\"$domain.*\"}[5m])",
     "legendFormat": "{{instance_name}}--({{instance}})- read"
    }
   ]
  },
  {
   "title": "Flush requests",
   "type": "graph",
   "description": "Total flush requests from a block device.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_block_stats_flush_requests_total{instance=~\"$instance.*\", instance_name=~\"$vm_name\"}[5m])",
     "legendFormat": "{{instance_name}}--({{instance}})"
    }
   ]
  },
  {
   "title": "Physical size of image",
   "type": "graph",
   "description": "Physical size in bytes of the container of the backing image.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_block_stats_physicalsize_bytes{instance=~\"$instance.*\", instance_name=~\"$vm_name\"}",
     "legendFormat": "{{instance_name}}--({{instance}})"
    }
   ]
  },
  {
   "title": "Flush time",
   "type": "graph",
   "description": "Total time (ns) spent on cache flushing to a block device, in ns, that is, 1/1,000,000,000 of a second, or 10−9 seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_block_stats_flush_time_seconds_total{instance=~\"$instance.*\", instance_name=~\"$vm_name\"}[5m])",
     "legendFormat": "{{instance_name}}--({{instance}})"
    }
   ]
  },
  {
   "title": "Image allocation",
   "type": "graph",
   "description": "Offset of the highest written sector on a block device.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_block_stats_allocation{instance=~\"$instance.*\", instance_name=~\"$vm_name\"}",
     "legendFormat": "{{instance_name}}--({{instance}})"
    }
   ]
  },
  {
   "title": "Logical size of the block device\t",
   "type": "graph",
   "description": "Logical size in bytes of the block device\tbacking image.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_block_stats_capacity_bytes{instance=~\"$instance.*\", instance_name=~\"$vm_name\"}",
     "legendFormat": "{{instance_name}}--({{instance}})"
    }
   ]
  }
 ]
}