{
 "title": "Cloud Monitoring",
 "description": "Openstack dashboard using the Openstack Exporter (https://github.com/Linaro/openstack-exporter)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   { "name": "datacenter", "label": "datacenter", "query": { "query": "label_values(datacenter)" } }
  ]
 },
 "panels": [
  { "title": "Resource Usage Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "interval" },
  {
   "title": "Projects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_identity_projects{datacenter=~\"$datacenter.*\"}"
    }
   ]
  },
  {
   "title": "Images",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_glance_images{datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "Flavors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_flavors{datacenter=~\"$datacenter.*\"}"
    }
   ]
  },
  {
   "title": "Total VMs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(openstack_nova_total_vms{datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "Floating IPs Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_neutron_floating_ips{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Networks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_neutron_networks{datacenter=~\"$datacenter.*\"}"
    }
   ]
  },
  {
   "title": "Routers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_neutron_routers{datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "% vCPU Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(openstack_nova_vcpus_used{datacenter=~\"$datacenter.*\"})/sum(openstack_nova_vcpus_available{datacenter=~\"$datacenter.*\"}*4))*100"
    }
   ]
  },
  {
   "title": "Total vCPU Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_vcpus_used{datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "Running VMs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_running_vms{datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "Subnets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_neutron_subnets{datacenter=~\"$datacenter.*\"}"
    }
   ]
  },
  {
   "title": "% Memory Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(openstack_nova_memory_used_bytes{datacenter=~\"$datacenter.*\"})/sum(openstack_nova_memory_available_bytes{datacenter=~\"$datacenter.*\"}))*100"
    }
   ]
  },
  {
   "title": "Total Memory Used (GiB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_memory_used_bytes{datacenter=~\"$datacenter.*\"})/ 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Total vCPU Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_vcpus_available{datacenter=~\"$datacenter.*\"})*4"
    }
   ]
  },
  {
   "title": "Total Memory Available (GiB)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 13, "x": 11, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_memory_available_bytes{datacenter=~\"$datacenter.*\"})/ 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Service status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nova agents down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openstack_nova_agent_state{adminState=\"enabled\",datacenter=~\"$datacenter.*\"})-sum(openstack_nova_agent_state{adminState=\"enabled\",datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "Nova agent status",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 14 },
   "targets": [
    {
     "expr": "openstack_nova_agent_state{adminState=\"enabled\",datacenter=~\"$datacenter.*\"}"
    }
   ]
  },
  {
   "title": "Nova agents up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_agent_state{adminState=\"enabled\",datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "Neutron agents down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(openstack_neutron_agent_state{adminState=\"up\",datacenter=~\"$datacenter.*\"})-sum(openstack_neutron_agent_state{adminState=\"up\",datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "Neutron agent status",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 22 },
   "targets": [
    {
     "expr": "openstack_neutron_agent_state{datacenter=~\"$datacenter.*\"}"
    }
   ]
  },
  {
   "title": "Neutron agents up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(openstack_neutron_agent_state{adminState=\"up\",datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "Glance agents Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(openstack_glance_up{datacenter=~\"$datacenter.*\"}==0) or vector(0)"
    }
   ]
  },
  {
   "title": "Glance agent status",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "openstack_glance_up{datacenter=~\"$datacenter.*\"}"
    }
   ]
  },
  {
   "title": "Glance agents up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(openstack_glance_up{datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "Keystone agents Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(openstack_identity_up{datacenter=~\"$datacenter.*\"}==0) or vector(0)"
    }
   ]
  },
  {
   "title": "Keystone agent status",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "openstack_identity_up{datacenter=~\"$datacenter.*\"}"
    }
   ]
  },
  {
   "title": "Keystone agents Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(openstack_identity_up{datacenter=~\"$datacenter.*\"}) "
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overall memory usage (TiB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(openstack_nova_memory_used_bytes{datacenter=~\"$datacenter.*\"})/ 1024 / 1024 / 1024 / 1024",
     "legendFormat": "memory in use"
    },
    {
     "expr": "sum(openstack_nova_memory_available_bytes{datacenter=~\"$datacenter.*\"}) / 1024 / 1024 / 1024 / 1024",
     "legendFormat": "memory available"
    }
   ]
  },
  {
   "title": "Overall CPU cores usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(openstack_nova_vcpus_used{datacenter=~\"$datacenter.*\"})",
     "legendFormat": "used vcpu cores"
    },
    {
     "expr": "sum(openstack_nova_vcpus{datacenter=~\"$datacenter.*\"})",
     "legendFormat": "total vcpu cores"
    }
   ]
  },
  {
   "title": "Local Storage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(openstack_nova_local_storage_used_bytes{datacenter=~\"$datacenter.*\"})/1024/1024/1024/1024/1024",
     "legendFormat": "local storage used"
    },
    {
     "expr": "sum(openstack_nova_local_storage_available_bytes{datacenter=~\"$datacenter.*\"})/1024/1024/1024/1024/1024",
     "legendFormat": "local storage available"
    }
   ]
  },
  {
   "title": "Neutron Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(openstack_neutron_floating_ips{datacenter=~\"$datacenter.*\"}) ",
     "legendFormat": "floating ips"
    },
    {
     "expr": "avg(openstack_neutron_networks{datacenter=~\"$datacenter.*\"})",
     "legendFormat": "networks"
    },
    {
     "expr": "avg(openstack_neutron_security_groups{datacenter=~\"$datacenter.*\"})",
     "legendFormat": "security groups"
    },
    {
     "expr": "avg(openstack_neutron_subnets{datacenter=~\"$datacenter.*\"})",
     "legendFormat": "subnets"
    }
   ]
  },
  {
   "title": "Keystone stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(openstack_identity_projects{datacenter=~\"$datacenter.*\"})",
     "legendFormat": "projects"
    },
    {
     "expr": "avg(openstack_identity_users{datacenter=~\"$datacenter.*\"})",
     "legendFormat": "users"
    },
    {
     "expr": "avg(openstack_identity_groups{datacenter=~\"$datacenter.*\"})",
     "legendFormat": "groups"
    }
   ]
  },
  {
   "title": "Virtual Machines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(openstack_nova_running_vms{datacenter=~\"$datacenter.*\"})",
     "legendFormat": "running vms"
    },
    {
     "expr": "sum(openstack_nova_total_vms{datacenter=~\"$datacenter.*\"})",
     "legendFormat": "total vms"
    }
   ]
  },
  {
   "title": "Glance Images",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(openstack_glance_images{datacenter=~\"$datacenter.*\"})",
     "legendFormat": "images"
    }
   ]
  }
 ]
}