{
 "title": "Cost Optimization",
 "description": "This is complete dashboard to monitor libvirt hypervisors and virtual machines",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   { "name": "datacenter", "label": "datacenter", "query": { "query": "label_values(datacenter)" } },
   { "name": "interval", "query": "1m,10m,1h,1d,7d,14d" },
   { "name": "Threshold" }
  ]
 },
 "panels": [
  {
   "title": "POWER OFF VM-More then  $interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(libvirt_domain_info_vstate{uuid=~\".+\", datacenter=~\"$datacenter.*\"}[$interval])== 5",
     "legendFormat": "{{datacenter}}--{{domain}}--{{host}}--{{flavor}}"
    }
   ]
  },
  {
   "title": "Memory used less then $Threshold % for past $interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max_over_time(libvirt_domain_memory_stats_used_percent{uuid=~\".+\", datacenter=~\"$datacenter.*\"}[$interval]) < $Threshold",
     "legendFormat": "{{datacenter}}--{{domain}}--{{host}}--{{flavor}}"
    }
   ]
  },
  {
   "title": "VM with less then  $Threshold IOPS (R+W)  for $interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max_over_time(irate(libvirt_domain_block_stats_write_requests_total{uuid=~\".+\", datacenter=~\"$datacenter.*\"}[5m]) [$interval:]) + max_over_time(irate(libvirt_domain_block_stats_read_requests_total{uuid=~\".+\", datacenter=~\"$datacenter.*\"}[5m]) [$interval:]) < $Threshold",
     "legendFormat": "{{datacenter}}--{{domain}}--{{host}}--{{flavor}}"
    }
   ]
  },
  {
   "title": "CPU Utilization less then $Threshold for past $interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max_over_time(irate(libvirt_domain_info_cpu_time_seconds_total{uuid=~\".+\"}[5m]) [$interval:]) *100 / 1000000000 / libvirt_domain_info_virtual_cpus{uuid=~\".+\"} < $Threshold",
     "legendFormat": "{{datacenter}}--{{domain}}--{{host}}--{{flavor}}"
    }
   ]
  }
 ]
}