{
 "title": "IPMI Sensor Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "IPMI data🔍 ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPMI Sensors State",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ipmi_bmc_info{instance=~\".*\"}",
       "legendFormat": "Power Status"
      }
     ]
    },
    {
     "title": "IPMI Sensors State",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ipmi_sensor_state{instance=~\".*\"}",
       "legendFormat": "Power Status"
      }
     ]
    }
   ]
  },
  {
   "title": "Temperature🌦️ ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperatures",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "ipmi_temperature_celsius{instance=~\".*\"}",
       "legendFormat": "Power Status"
      }
     ]
    },
    {
     "title": "Temperature State",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "ipmi_temperature_state{instance=~\".*\"}",
       "legendFormat": "Power Status"
      }
     ]
    }
   ]
  },
  {
   "title": "Fan Status🪭 ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fan Speed State",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "ipmi_fan_speed_state{instance=~\".*\"}",
       "legendFormat": "Power Status"
      }
     ]
    },
    {
     "title": "Fan speed in rotations per minute",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "ipmi_fan_speed_rpm{instance=~\".*\"}",
       "legendFormat": "Power Status"
      }
     ]
    }
   ]
  },
  { "title": "Power Status💡 ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Power State",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "ipmi_power_state{instance=~\".*\"}",
     "legendFormat": "Power Status"
    }
   ]
  },
  {
   "title": "Reported state of a voltage sensor",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "ipmi_voltage_state{instance=~\".*\"}",
     "legendFormat": "Power Status"
    }
   ]
  },
  {
   "title": "Power reading in Watts",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "ipmi_power_watts{instance=~\".*\"}",
     "legendFormat": "Power Status"
    }
   ]
  },
  {
   "title": "Voltage reading in Volts",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "ipmi_voltage_volts{instance=~\".*\"}",
     "legendFormat": "Power Status"
    }
   ]
  },
  {
   "title": "Power Consumption watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}