{
 "title": "IPMI Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datacenter", "label": "datacenter", "query": { "query": "label_values(datacenter)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(ipmi_bmc_info{datacenter=~\"$datacenter.*\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Power Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ipmi_chassis_power_state", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Machine Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 4, "y": 0 },
   "targets": [
    { "expr": "ipmi_bmc_info" }
   ]
  },
  {
   "title": "Fan Speed State",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_fan_speed_state{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fan speed in rotations per minute",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_fan_speed_rpm{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power State",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_power_state{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power reading in Watts",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_power_watts{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power Consumption watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IPMI Sensors State",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "ipmi_sensor_state{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Temperature State",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "ipmi_temperature_state{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reported state of a voltage sensor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_voltage_state{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Voltage reading in Volts",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_voltage_volts{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}