{
 "title": "LoadBalancer Monitoring",
 "description": "Dynamic Dashboard for HAProxy ",
 "tags": [
  "haproxy",
  "proxy",
  "reverseproxy",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "datacenter", "label": "datacenter", "query": { "query": "label_values(datacenter)" } },
   {
    "name": "node",
    "label": "LoadBalancer",
    "query": {
     "query": "label_values(haproxy_up{instance=~\".*:9101\",env=\"$env\"},alias)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Proxy Status",
   "type": "graph",
   "description": "0 = DOWN\n1 = UP",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{alias=~\"$node\",instance=~\".*9101\",datacenter=\"$datacenter\"}",
     "legendFormat": "UP: {{alias}}"
    }
   ]
  },
  {
   "title": "Proxy Availability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "round((sum(avg_over_time(haproxy_up{alias=~\"$node\",instance=~\".*9101\",datacenter=\"$datacenter\"})) + 0.5) /2)",
     "legendFormat": "Availability"
    }
   ]
  },
  {
   "title": "Exporter (uptime)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{alias=~\"$node\",instance=~\".*9101\",datacenter=\"$datacenter\"})",
     "legendFormat": "Uptime: {{alias}}"
    }
   ]
  },
  {
   "title": "Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP Response Codes (Total): $node",
   "type": "timeseries",
   "description": "- haproxy_frontend_http_responses_total = Total of HTTP responses.",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(haproxy_frontend_http_responses_total{alias=~\"$node\",datacenter=\"$datacenter\"}[1m])",
     "legendFormat": "Frontend: [ {{code}} ] ({{alias}}) {{frontend}} "
    }
   ]
  },
  {
   "title": "Error - HTTP Response Codes Ratio (4xx, 5xx): $node",
   "type": "timeseries",
   "description": "- haproxy_frontend_http_responses_total = Total of HTTP responses.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(code,alias,frontend)(irate(haproxy_frontend_http_responses_total{alias=~\"$node\",code=\"5xx\",datacenter=\"$datacenter\"}[1m])) / sum by(code,alias,frontend)(irate(haproxy_frontend_http_responses_total{alias=~\"$node\",datacenter=\"$datacenter\"}[1m]))",
     "legendFormat": "Error 5xx Ratio: {{alias}} [ {{frontend}} ]"
    },
    {
     "expr": "sum by(code,alias,frontend)(irate(haproxy_frontend_http_responses_total{alias=~\"$node\",code=\"4xx\",datacenter=\"$datacenter\"}[1m])) / sum by(code,alias,frontend)(irate(haproxy_frontend_http_responses_total{alias=~\"$node\",datacenter=\"$datacenter\"}[1m]))",
     "legendFormat": "Error 4xx Ratio: {{alias}} [ {{frontend}} ] "
    }
   ]
  },
  {
   "title": "Error - Request Errors/ Requests Denied: $node",
   "type": "timeseries",
   "description": "- haproxy_frontend_requests_denied_total = Total of requests denied for security.\n- haproxy_frontend_request_errors_total = Total of request errors.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes(haproxy_frontend_requests_denied_total{alias=~\"$node\",datacenter=\"$datacenter\"}[5m])",
     "legendFormat": "Requests Denied: {{alias}}   [ {{frontend}} ]"
    },
    {
     "expr": "changes(haproxy_frontend_request_errors_total{alias=~\"$node\",datacenter=\"$datacenter\"}[5m])",
     "legendFormat": "Requests Errors: {{alias}}  [ {{frontend}} ]"
    }
   ]
  },
  {
   "title": "Utilization - Current Sessions/s : $node",
   "type": "timeseries",
   "description": "- haproxy_frontend_current_session_rate = Current number of sessions per second over last elapsed second.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "haproxy_frontend_current_session_rate{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Rate: {{alias}}   [ {{frontend}} ]"
    }
   ]
  },
  {
   "title": "Utilization - IN/ OUT (Bytes): $node",
   "type": "timeseries",
   "description": "- haproxy_frontend_bytes_in_total = Current total of incoming bytes.\n- haproxy_frontend_bytes_out_total Current total of outgoing bytes.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(haproxy_frontend_bytes_in_total{alias=~\"$node\",datacenter=\"$datacenter\"}[5m])",
     "legendFormat": "IN: {{alias}} [ {{frontend}} ]"
    },
    {
     "expr": "irate(haproxy_frontend_bytes_out_total{alias=~\"$node\",datacenter=\"$datacenter\"}[5m])",
     "legendFormat": "OUT: {{alias}} [ {{frontend}} ]"
    }
   ]
  },
  {
   "title": "Utilization - Frontend (Connections %): $node",
   "type": "timeseries",
   "description": "- Connection Utilization (%):\n   - WARNING = 60%\n   - CRITICAL = 70%\n\n- slim [LFBS]: configured session limit (maxconn from haproxy.conf)\n- scur [LFBS]: current sessions\n- stot [LFBS]: cumulative number of sessions\n- smax [LFBS]: max sessions",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "haproxy_frontend_current_sessions{alias=~\"$node\",datacenter=\"$datacenter\"} / haproxy_frontend_limit_sessions{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "{{alias}}: [ {{frontend}} ]"
    }
   ]
  },
  {
   "title": "Frontend (Connections: Limit, Max, Current): $node",
   "type": "timeseries",
   "description": "- slim [LFBS]: configured session limit (maxconn from haproxy.conf)\n- scur [LFBS]: current sessions\n- stot [LFBS]: cumulative number of sessions\n- smax [LFBS]: max sessions",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "haproxy_frontend_current_sessions{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Current: {{alias}}: [ {{frontend}} ]"
    },
    {
     "expr": "haproxy_frontend_limit_sessions{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Limit: {{alias}}: [ {{frontend}} ]"
    }
   ]
  },
  {
   "title": "Backend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backend Status: $node",
   "type": "timeseries",
   "description": "- haproxy_backend_up = Current health status of the backend (1 = UP, 0 = DOWN).",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "haproxy_backend_up{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "UP: {{alias}} [ {{backend}} ]"
    }
   ]
  },
  {
   "title": "Backend Weight: $node",
   "type": "timeseries",
   "description": "- haproxy_backend_weight = Total weight of the servers in the backend.",
   "gridPos": { "h": 17, "w": 8, "x": 8, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "haproxy_backend_weight{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Weight: {{alias}} [ {{backend}} ]"
    }
   ]
  },
  {
   "title": "Backend Active Servers: $node",
   "type": "timeseries",
   "description": "- haproxy_backend_current_server = Current number of active servers",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "haproxy_backend_current_server{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Active: {{alias}} [ {{backend}} ]"
    }
   ]
  },
  {
   "title": "HTTP Response Codes (Total): $node",
   "type": "timeseries",
   "description": "haproxy_backend_http_responses_total = Total of HTTP responses.",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(haproxy_backend_http_responses_total{alias=~\"$node\",datacenter=\"$datacenter\"}[5m])",
     "legendFormat": "HTTP: {{alias}} [ {{code}} ] ( {{backend}} ) "
    }
   ]
  },
  {
   "title": "Error - Response Errors/ Connection Errors: $node",
   "type": "timeseries",
   "description": "- haproxy_backend_connection_errors_total = Total of connection errors.\n-  haproxy_backend_response_errors_total Total of response errors.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes(haproxy_backend_connection_errors_total{alias=~\"$node\",datacenter=\"$datacenter\"}[5m])",
     "legendFormat": "Connection Errors: {{alias}} [ {{backend}} ]"
    },
    {
     "expr": "changes(haproxy_backend_response_errors_total{alias=~\"$node\",datacenter=\"$datacenter\"}[5m])",
     "legendFormat": "Response Errors: {{alias}} [ {{backend}} ]"
    }
   ]
  },
  {
   "title": "Utilization - IN/ OUT (Bytes): $node",
   "type": "timeseries",
   "description": "- haproxy_backend_bytes_in_total = Current total of incoming bytes.\n- haproxy_backend_bytes_out_total Current total of outgoing bytes.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(haproxy_backend_bytes_in_total{alias=~\"$node\",datacenter=\"$datacenter\"}[5m])",
     "legendFormat": "IN: {{alias}} [ {{backend}} ]"
    },
    {
     "expr": "irate(haproxy_backend_bytes_out_total{alias=~\"$node\",datacenter=\"$datacenter\"}[5m])",
     "legendFormat": "OUT: {{alias}} [ {{backend}} ]"
    }
   ]
  },
  {
   "title": "Availability - Redispatch Warnings/ Retry Warnings: $node",
   "type": "timeseries",
   "description": "- haproxy_backend_retry_warnings_total = Total of retry warnings.\n- haproxy_backend_redispatch_warnings_total = Total of redispatch warnings.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(haproxy_backend_redispatch_warnings_total{alias=~\"$node\",datacenter=\"$datacenter\"}[5m])",
     "legendFormat": "Redispatch Warnings: {{alias}} [ {{backend}} ]"
    },
    {
     "expr": "increase(haproxy_backend_retry_warnings_total{alias=~\"$node\",datacenter=\"$datacenter\"}[5m])",
     "legendFormat": "Retry Warnings: {{alias}} [ {{backend}} ]"
    }
   ]
  },
  {
   "title": "Saturation - Number of queued requests not assigned to any server (Current/ Maximum): $node",
   "type": "timeseries",
   "description": "- haproxy_backend_max_queue = Maximum observed number of queued requests not assigned to any server.\n- haproxy_backend_current_queue = Current number of queued requests not assigned to any server.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "haproxy_backend_max_queue{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Max Queue: {{alias}}  [ {{backend}} ]"
    },
    {
     "expr": "haproxy_backend_current_queue{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Current Queue: {{alias}}  [ {{backend}} ]"
    }
   ]
  },
  {
   "title": "Throughput - HTTP Average Time (s) for (Connect/ Response/ Queue/ Total): $node",
   "type": "timeseries",
   "description": "- haproxy_backend_http_connect_time_average_seconds Avg. HTTP connect time for last 1024 successful connections.\n- haproxy_backend_http_queue_time_average_seconds Avg. HTTP queue time for last 1024 successful connections.\n- haproxy_backend_http_response_time_average_seconds Avg. HTTP response time for last 1024 successful connections.\n- haproxy_backend_http_total_time_average_seconds Avg. HTTP total time for last 1024 successful connections.",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "haproxy_backend_http_connect_time_average_seconds{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Connect Time: {{alias}} [ {{backend}} ]"
    },
    {
     "expr": "haproxy_backend_http_queue_time_average_seconds{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Queue Time: {{alias}} [ {{backend}} ]"
    },
    {
     "expr": "haproxy_backend_http_response_time_average_seconds{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Response Time: {{alias}} [ {{backend}} ]"
    },
    {
     "expr": "haproxy_backend_http_total_time_average_seconds{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Total Time: {{alias}} [ {{backend}} ]"
    }
   ]
  },
  {
   "title": "Utilization - Backend (Connections %): $node",
   "type": "timeseries",
   "description": "- Connection Utilization (%):\n   - WARNING = 60%\n   - CRITICAL = 70%\n\n- slim [LFBS]: configured session limit (maxconn from haproxy.conf)\n- scur [LFBS]: current sessions\n- stot [LFBS]: cumulative number of sessions\n- smax [LFBS]: max sessions",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "haproxy_backend_current_sessions{alias=~\"$node\",datacenter=\"$datacenter\"} / haproxy_backend_limit_sessions{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "{{alias}}: [ {{backend}} ]"
    }
   ]
  },
  {
   "title": "Utilization - Current Sessions/s : $node",
   "type": "timeseries",
   "description": "- haproxy_backend_current_session_rate = Current number of sessions per second over last elapsed second.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "haproxy_backend_current_session_rate{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Rate: {{alias}}   [ {{backend}} ]"
    }
   ]
  },
  {
   "title": "Backend (Connections: Limit, Max, Current): $node",
   "type": "timeseries",
   "description": "- slim [LFBS]: configured session limit (maxconn from haproxy.conf)\n- scur [LFBS]: current sessions\n- stot [LFBS]: cumulative number of sessions\n- smax [LFBS]: max sessions",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "haproxy_backend_current_sessions{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Current: {{alias}}: [ {{backend}} ]"
    },
    {
     "expr": "haproxy_backend_limit_sessions{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Limit: {{alias}}: [ {{backend}} ]"
    }
   ]
  },
  {
   "title": "Error - HTTP Response Codes Ratio (4xx, 5xx): $node",
   "type": "timeseries",
   "description": "- haproxy_backend_http_responses_total = Total of HTTP responses.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 228 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(code,alias,backend)(irate(haproxy_backend_http_responses_total{alias=~\"$node\",code=\"5xx\",datacenter=\"$datacenter\"}[1m])) / sum by(code,alias,backend)(irate(haproxy_backend_http_responses_total{alias=~\"$node\",datacenter=\"$datacenter\"}[1m]))",
     "legendFormat": "Error 5xx Ratio: {{alias}} [ {{backend}}  ]"
    },
    {
     "expr": "sum by(code,alias,backend)(irate(haproxy_backend_http_responses_total{alias=~\"$node\",code=\"4xx\",datacenter=\"$datacenter\"}[1m])) / sum by(code,alias,backend)(irate(haproxy_backend_http_responses_total{alias=~\"$node\",datacenter=\"$datacenter\"}[1m]))",
     "legendFormat": "Error 4xx Ratio: {{alias}} [ {{backend}}  ]"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 240 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server Status: $node",
   "type": "timeseries",
   "description": "- haproxy_server_up = Current health status of the server (1 = UP, 0 = DOWN).",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "haproxy_server_up{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "UP: {{alias}} [ {{server}} ]"
    }
   ]
  },
  {
   "title": "Server Weight: $node",
   "type": "timeseries",
   "description": "- haproxy_server_weight = Current weight of the server.",
   "gridPos": { "h": 17, "w": 8, "x": 8, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "haproxy_server_weight{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Weight: {{alias}} [ {{server}} ]"
    }
   ]
  },
  {
   "title": "Server Downtime (s): $node",
   "type": "timeseries",
   "description": "- haproxy_server_downtime_seconds_total = Total downtime in seconds.",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "haproxy_server_downtime_seconds_total{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Downtime: {{alias}}  [ {{server}} ]"
    }
   ]
  },
  {
   "title": "Health Check Duration (ms): $node",
   "type": "graph",
   "description": "- haproxy_server_check_duration_milliseconds = Previously run health check duration, in milliseconds",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 258 },
   "yaxes": [
    { "format": "ms", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_check_duration_milliseconds{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Health Check: {{alias}} [ {{server}} ]"
    }
   ]
  },
  {
   "title": "Failed Health Checks: $node",
   "type": "timeseries",
   "description": "- haproxy_server_check_failures_total = Total number of failed health checks.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 258 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(haproxy_server_check_failures_total{alias=~\"$node\",datacenter=\"$datacenter\"}[5m])",
     "legendFormat": "Failures Check: {{alias}} [ {{server}} ]"
    }
   ]
  },
  {
   "title": "Utilization - Current Sessions/s : $node",
   "type": "timeseries",
   "description": "- haproxy_server_current_session_rate = Current number of sessions per second over last elapsed second.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 273 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "haproxy_server_current_session_rate{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Rate: {{alias}}   [ {{server}} ]"
    }
   ]
  },
  {
   "title": "Error - HTTP Response Codes Ratio (4xx, 5xx): $node",
   "type": "timeseries",
   "description": "- haproxy_backend_http_responses_total = Total of HTTP responses.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 285 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(code,alias,server)(irate(haproxy_server_http_responses_total{alias=~\"$node\",datacenter=\"$datacenter\",code=\"5xx\"}[1m])) / sum by(code,alias,server)(irate(haproxy_server_http_responses_total{alias=~\"$node\",datacenter=\"$datacenter\"}[1m]))",
     "legendFormat": "Error 5xx Ratio: {{alias}} [ {{server}}  ]"
    },
    {
     "expr": "sum by(code,alias,server)(irate(haproxy_server_http_responses_total{alias=~\"$node\",datacenter=\"$datacenter\",code=\"4xx\"}[1m])) / sum by(code,alias,server)(irate(haproxy_server_http_responses_total{alias=~\"$node\",datacenter=\"$datacenter\"}[1m]))",
     "legendFormat": "Error 4xx Ratio: {{alias}} [ {{server}}  ]"
    }
   ]
  },
  {
   "title": "HTTP Response Codes (Total): $node",
   "type": "timeseries",
   "description": "- haproxy_server_http_responses_total = Total of HTTP responses.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 297 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(haproxy_server_http_responses_total{alias=~\"$node\",datacenter=\"$datacenter\"}[5m])",
     "legendFormat": "HTTP: {{alias}} [ {{code}} ] ( {{server}} )"
    }
   ]
  },
  {
   "title": "Throughput IN/ OUT (Bytes): $node",
   "type": "timeseries",
   "description": "- haproxy_server_bytes_out_total = Current total of outgoing bytes.\n- haproxy_server_bytes_in_total = Current total of incoming bytes.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 311 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(haproxy_server_bytes_in_total{alias=~\"$node\",datacenter=\"$datacenter\"}[5m])",
     "legendFormat": "IN: {{alias}}  [ {{backend}} ]"
    },
    {
     "expr": "irate(haproxy_server_bytes_out_total{alias=~\"$node\",datacenter=\"$datacenter\"}[5m])",
     "legendFormat": "OUT: {{alias}}  [ {{backend}} ]"
    }
   ]
  },
  {
   "title": "Response Errors/ Redispatch Warnings/ Retry Warnings: $node",
   "type": "timeseries",
   "description": "- haproxy_server_retry_warnings_total = Total of retry warnings.\n-  haproxy_server_response_errors_total = Total of response errors.\n- haproxy_server_redispatch_warnings_total = Total of redispatch warnings.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 319 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(haproxy_server_response_errors_total{alias=~\"$node\",datacenter=\"$datacenter\"}[5m])",
     "legendFormat": "Response Errors: {{alias}} [ {{server}} ]"
    },
    {
     "expr": "increase(haproxy_server_redispatch_warnings_total{alias=~\"$node\",datacenter=\"$datacenter\"}[5m])",
     "legendFormat": "Redispatch Warnings: {{alias}} [ {{server}} ]"
    },
    {
     "expr": "increase(haproxy_server_retry_warnings_total{alias=~\"$node\",datacenter=\"$datacenter\"}[5m])",
     "legendFormat": "Retry Warnings: {{alias}} [ {{server}} ]"
    }
   ]
  },
  {
   "title": "Errors Connection: $node",
   "type": "timeseries",
   "description": "- haproxy_server_connection_errors_total = Total of connection errors.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 333 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes(haproxy_server_connection_errors_total{alias=~\"$node\",datacenter=\"$datacenter\"}[5m])",
     "legendFormat": "Connection Errors: {{alias}} [ {{server}} ]"
    }
   ]
  },
  {
   "title": "Number of queued requests assigned to this server (Current/ Maximum): $node",
   "type": "timeseries",
   "description": "- haproxy_server_current_queue = Current number of queued requests assigned to this server.\n- haproxy_server_max_queue = Maximum observed number of queued requests assigned to this server.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 342 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "haproxy_server_max_queue{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Max Queue: {{alias}} [ {{backend}} ]",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "haproxy_server_current_queue{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Current Queue: {{alias}} [ {{backend}} ]",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Server (Connections: Limit, Max, Current): $node",
   "type": "timeseries",
   "description": "- slim [LFBS]: configured session limit (maxconn from haproxy.conf)\n- scur [LFBS]: current sessions\n- stot [LFBS]: cumulative number of sessions\n- smax [LFBS]: max sessions",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 350 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "haproxy_server_current_sessions{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Current: {{alias}}: [ {{server}} ]"
    },
    {
     "expr": "haproxy_server_limit_sessions{alias=~\"$node\",datacenter=\"$datacenter\"}",
     "legendFormat": "Limit: {{alias}}: [ {{server}} ]"
    }
   ]
  }
 ]
}