{
 "title": "Memcached Monitoring",
 "description": "Prometheus dashboard for memcached servers",
 "tags": [
  "prometheus",
  "memcached"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   { "name": "datacenter", "label": "datacenter", "query": { "query": "label_values(datacenter)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(memcached_up{datacenter=~\"$datacenter.*\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "% Hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (memcached_commands_total{instance=~\"$node\", status=\"miss\"})  / sum (memcached_commands_total{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (memcached_current_connections{instance=~\"$node\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Get / Set ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (memcached_commands_total{instance=~\"$node\", command=\"set\"}) / sum (memcached_commands_total{instance=~\"$node\", command=\"get\"})"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (memcached_commands_total{instance=~\"$node\"}) by (command)"
    }
   ]
  },
  {
   "title": "evicts / reclaims",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(memcached_items_evicted_total{instance=~\"$node\"})"
    },
    {}
   ]
  },
  {
   "title": "Read / written bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(memcached_read_bytes_total{instance=~\"$node\"}[5m]))"
    },
    {
     "expr": "irate(memcached_written_bytes_total{instance=~\"$node\"}[10m])"
    }
   ]
  },
  {
   "title": "Total memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(memcached_current_bytes{instance=~\"$node\"}) / sum(memcached_limit_bytes{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Items in cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (memcached_current_items{instance=~\"$node\"})"
    }
   ]
  }
 ]
}