{
 "title": "Storage Monitoring",
 "description": "Ceph Cluster overview.\r\n",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   { "name": "datacenter", "label": "datacenter", "query": { "query": "label_values(datacenter)" } },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CLUSTER STATE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "description": "Ceph Cluster Leader and Ceph Health",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_health_status{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{datacenter=~\"$datacenter.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{datacenter=~\"$datacenter.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{datacenter=~\"$datacenter.*\"}"
    }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceph_cluster_total_bytes{datacenter=~\"$datacenter.*\"}-ceph_cluster_total_used_bytes{datacenter=~\"$datacenter.*\"})/ceph_cluster_total_bytes{datacenter=~\"$datacenter.*\"}"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_objects{datacenter=~\"$datacenter.*\"}"
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_op_w_in_bytes{datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "Bytes Read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_op_r_out_bytes{datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate='firing',datacenter=~\"$datacenter.*\"}) OR vector(0)"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w{datacenter=~\"$datacenter.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r{datacenter=~\"$datacenter.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{datacenter=~\"$datacenter.*\"}"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_objects{datacenter=~\"$datacenter.*\"}"
    }
   ]
  },
  {
   "title": "Mon Session Num",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_mon_num_sessions{datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_mon_quorum_status{datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "OSD STATE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OSDs OUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{datacenter=~\"$datacenter.*\"}) - count(ceph_osd_in{datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{datacenter=~\"$datacenter.*\"} == 0.0) OR vector(0)"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_up{datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "OSDs IN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_in{datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "Avg PGs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_numpg{datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "Avg Apply Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "Avg Commit Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms{datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "Avg Op Write Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_w_latency_sum{datacenter=~\"$datacenter.*\"}[5m]) / rate(ceph_osd_op_w_latency_count{datacenter=~\"$datacenter.*\"}[5m]) >= 0)"
    }
   ]
  },
  {
   "title": "Avg  Op Read Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_r_latency_sum{datacenter=~\"$datacenter.*\"}[5m])/rate(ceph_osd_op_r_latency_count{datacenter=~\"$datacenter.*\"}[5m]) >= 0)"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top Sluggish OSD's",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "topk(5,sort_desc(ceph_osd_apply_latency_ms{datacenter=~\"$datacenter.*\"} + ceph_osd_commit_latency_ms{datacenter=~\"$datacenter.*\"}))"
    }
   ]
  },
  {
   "title": "Down OSD's",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "ceph_osd_up{datacenter=~\"$datacenter.*\"} != 1"
    }
   ]
  },
  {
   "title": "Ceph Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ceph OSD Versions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (ceph_version)(ceph_osd_metadata{datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "Ceph Mon Versions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (ceph_version)(ceph_mon_metadata{datacenter=~\"$datacenter.*\"})"
    }
   ]
  },
  {
   "title": "CLUSTER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Total Capacity"
    },
    {
     "expr": "ceph_cluster_total_bytes{datacenter=~\"$datacenter.*\"}-ceph_cluster_total_used_bytes{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "ceph_cluster_total_used_bytes{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w{datacenter=~\"$datacenter.*\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r{datacenter=~\"$datacenter.*\"}[5m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{datacenter=~\"$datacenter.*\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{datacenter=~\"$datacenter.*\"}[5m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Pool Quota Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_pool_quota_bytes{datacenter=~\"$datacenter.*\"}) *on (pool_id) group_left(name)(ceph_pool_metadata{datacenter=~\"$datacenter.*\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Objects Quota",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(ceph_pool_quota_objects{datacenter=~\"$datacenter.*\"}) *on (pool_id) group_left(name)(ceph_pool_metadata{datacenter=~\"$datacenter.*\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Objects Per Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(ceph_pool_objects{datacenter=~\"$datacenter.*\"}) *on (pool_id) group_left(name)(ceph_pool_metadata{datacenter=~\"$datacenter.*\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "OSD Type Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_bluestore_commit_lat_count{datacenter=~\"$datacenter.*\"}) ",
     "legendFormat": "BlueStore"
    },
    {
     "expr": "count(ceph_filestore_journal_latency_count{datacenter=~\"$datacenter.*\"})",
     "legendFormat": "FileStore"
    }
   ]
  },
  {
   "title": "OBJECTS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Objects in the Cluster",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_cluster_total_objects{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "PGs State",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceph_pg_active{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "ceph_pg_clean{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Clean"
    },
    {
     "expr": "ceph_pg_peering{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Peering"
    },
    {
     "expr": "ceph_pg_degraded{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Degraded"
    },
    {
     "expr": "ceph_pg_stale{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Stale"
    },
    {
     "expr": "ceph_unclean_pgs{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Unclean"
    },
    {
     "expr": "ceph_pg_undersized{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Undersized"
    },
    {
     "expr": "ceph_pg_incomplete{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Incomplete"
    },
    {
     "expr": "ceph_pg_forced_backfill{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Forced Backfill"
    },
    {
     "expr": "ceph_pg_inconsistent{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Inconsistent"
    },
    {
     "expr": "ceph_pg_forced_recovery{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Forced Recovery"
    },
    {
     "expr": "ceph_pg_creating{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Creating"
    },
    {
     "expr": "ceph_pg_wait_backfill{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Wait Backfill"
    },
    {
     "expr": "ceph_pg_deep{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Deep"
    },
    {
     "expr": "ceph_pg_scrubbing{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Scrubbing"
    },
    {
     "expr": "ceph_pg_recovering{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Recovering"
    },
    {
     "expr": "ceph_pg_repair{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Repair"
    },
    {
     "expr": "ceph_pg_down{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Down"
    },
    {
     "expr": "ceph_pg_peered{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Peered"
    },
    {
     "expr": "ceph_pg_backfill{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Backfill"
    },
    {
     "expr": "ceph_pg_remapped{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Remapped"
    },
    {
     "expr": "ceph_pg_backfill_toofull{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Backfill Toofull"
    }
   ]
  },
  {
   "title": "Stuck PGs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceph_pg_degraded{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Degraded"
    },
    {
     "expr": "ceph_pg_stale{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Stale"
    },
    {
     "expr": "ceph_pg_undersized{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "Undersized"
    }
   ]
  },
  {
   "title": "Recovery Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops{datacenter=~\"$datacenter.*\"}[$interval]))",
     "legendFormat": "OPS"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OSD Apply Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "ceph_osd_apply_latency_ms{datacenter=~\"$datacenter.*\"}"
    }
   ]
  },
  {
   "title": "OSD Commit Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "ceph_osd_commit_latency_ms{datacenter=~\"$datacenter.*\"}"
    }
   ]
  },
  {
   "title": "OSD Read Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r_latency_sum{datacenter=~\"$datacenter.*\"}[5m]) / rate(ceph_osd_op_r_latency_count{datacenter=~\"$datacenter.*\"}[5m]) >= 0"
    }
   ]
  },
  {
   "title": "OSD Write Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_w_latency_sum{datacenter=~\"$datacenter.*\"}[5m]) / rate(ceph_osd_op_w_latency_count{datacenter=~\"$datacenter.*\"}[5m]) >= 0"
    }
   ]
  },
  {
   "title": "Avg OSD  Op  Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_r_latency_sum{datacenter=~\"$datacenter.*\"}[5m]) / rate(ceph_osd_op_r_latency_count{datacenter=~\"$datacenter.*\"}[5m]) >= 0)",
     "legendFormat": "read"
    },
    {
     "expr": "avg(rate(ceph_osd_op_w_latency_sum{datacenter=~\"$datacenter.*\"}[5m]) / rate(ceph_osd_op_w_latency_count{datacenter=~\"$datacenter.*\"}[5m]) >= 0)",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "AVG OSD Apply + Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{datacenter=~\"$datacenter.*\"})",
     "legendFormat": "apply"
    },
    {
     "expr": "avg(ceph_osd_commit_latency_ms{datacenter=~\"$datacenter.*\"})",
     "legendFormat": "commit"
    }
   ]
  },
  {
   "title": "Node Statistics (NodeExporter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Active_anon_bytes{datacenter=~\"$datacenter.*\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(node_memory_Active_anon_bytes{datacenter=~\"$datacenter.*\"})",
     "legendFormat": "Cluster Memory Usage"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by(instance)(irate(node_cpu_seconds_total{job='node_exporter', mode!=\"idle\",instance=~'controller.*',datacenter=~\"$datacenter.*\"}[5m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_read_bytes_total{datacenter=~\"$datacenter.*\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_disk_written_bytes_total{datacenter=~\"$datacenter.*\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free Space in root filesystem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_free_bytes{mountpoint='/', device != 'rootfs',datacenter=~\"$datacenter.*\"})*100 / (node_filesystem_size_bytes{mountpoint='/', device != 'rootfs',datacenter=~\"$datacenter.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}