apiVersion: v2
appVersion: v1.94.0
description: Victoria Metrics Cluster version - high-performance, cost-effective and
  scalable TSDB, long-term remote storage for Prometheus
home: https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
keywords:
- victoriametrics
- vmcluster
- vmselect
- vminsert
- vmstorage
- tsdb
- monitoring
- kubernetes
- observability
- metrics
- metricsql
- timeseries
kubeVersion: '>=1.23.0-0'
name: victoria-metrics-cluster
sources:
- https://github.com/VictoriaMetrics/helm-charts
version: 0.11.4
# dependencies:
# - condition: vmAgent.enabled
#   name: victoria-metrics-agent
#   repository: 'file://components/vmAgent'
#   version: 0.8.40
