apiVersion: v1
kind: ConfigMap
metadata:
  name: datasource-configmap
  labels:
    grafana_datasource: "1"
  namespace: {{ .Release.Namespace | quote }}
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: victoria-metrics-k8s
        uid: victoria-metrics-k8s
        type: prometheus
        access: proxy
        orgId: 1
        isDefault: true
        editable: true
        url: http://vm-cluster-select:8481/select/0/prometheus/
      - name: prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        orgId: 1
        isDefault: false
        editable: true
        url: http://prometheus-server:80
      - name: loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki:3100
    